/*
 * DO NOT MODIFY. THIS CODE IS MACHINE GENERATED BY THE TANNHÄUSER PD COMPILER.
 */

#import <Foundation/Foundation.h>

@interface THtann : NSObject

- (id)initWithInputChannels:(NSInteger)numInputChannels outputChannels:(NSInteger)numOutputChannels
        blockSize:(NSInteger)blockSize sampleRate:(Float64)sampleRate andBasePath:(NSString *)basePath;

- (bool)sendMessageToReceiver:(NSString *)name atTime:(Float64)timestamp withFormatAndData:(NSString *)format, ...;

- (void)processWithInput:(Float32 *)inputBuffers output:(Float32 *)outputBuffers withBlockSize:(int)n;

- (float *)getTableBufferForName:(NSString *)tableName withLength:(int *)length resize:(BOOL)resize;

- (void)processBlock:(void(^)())block;

- (void)lock;

- (void)unlock;

@end
